### ISSUE TITLE
OS X - cannot run program "convert"

### ISSUE THREAD

**Issue by mg6maciej** [splatte/gradle-android-appiconoverlay#3] opened 2015-03-03 11:05 UTC
On OS X, after installing imagemagick with `brew install imagemagick`:
- when running from Android Studio, it says it cannot find "convert",
- when running with `./gradlew assemble` it hangs on overlayiconDebug task (we waited for 2 minutes)

When trying to run `convert` command from Terminal, it shows help, so I assume it works fine.

Any idea what can be wrong or how can we get more input to solve it?

**Comment by splatte** [comment] 2015-03-03 11:12
Yeah, the gradle process doesn't find my `convert` (which is in /opt/local/bin/convert, OSX and works in terminal, too) either, when using the default config. I have to specify the exact path:

```
appiconoverlay {
    imageMagick '/opt/local/bin/convert'
}
```

Failing with a meaningful error would be better than hanging infinitely.

**Comment by mg6maciej** [comment] 2015-03-03 11:28
Thanks for a very quick answer.

Do you have a suggestion how we could not hardcode it in build.gradle?

I'm running on Ubuntu and have it here: `/usr/bin/convert` and we also make debug builds with icon overlay on Travis-CI. I didn't even check where Travis has it, because it had imagemagick installed by default, which was a nice surprise.

Maybe fallback to running `convert` inside the plugin with absolute path `/opt/local/bin/convert` and `/usr/bin/convert`, when relative fails?

**Comment by splatte** [comment] 2015-03-03 11:44
The value for the "imageMagick" config defaults to "convert" (https://github.com/splatte/gradle-android-appiconoverlay/blob/master/src/main/groovy/com/github/splatte/android/AppIconOverlayPlugin.groovy#L61). This command is then executed here: https://github.com/splatte/gradle-android-appiconoverlay/blob/master/src/main/groovy/com/github/splatte/android/OverlayTask.groovy#L47

I didn't dig deep when I wrote this, but I was confused myself why it wouldn't find the binary in a $PATH location. Is there a different $PATH in use inside gradle? Why doesn't gradle find the same convert as I do in the terminal? Relevant groovy docs: http://groovy.codehaus.org/Process+Management & http://groovy.codehaus.org/groovy-jdk/java/lang/Process.html

Another way out: If `imageMagick` is still "convert", running `which convert` before and using the output to invoke ImageMagick yields a different result?

**Comment by mg6maciej** [comment] 2015-03-03 12:19
That sounds good. We would do something like:

```
appiconoverlay {
    imageMagick "${commandLine 'which', 'convert'}"
}
```

I just don't know how to construct, so gradle understands it.

If you can make a call to `which` inside the plugin, that would be even better for users.

**Comment by splatte** [comment] 2015-03-07 10:45
> when running from Android Studio, it says it cannot find "convert",

I have the same behavior in AS. however, when I run from commandline, it does find "convert" just like that without further config. I am poking around a bit to find why gradle within AS wouldn't find it.

```
logger.debug(['bash', '-c', 'echo $PATH' ].execute().text)
logger.debug(System.getenv('PATH'))
```

Within AS, I get:

```
10:55:43.945 [DEBUG] [org.gradle.api.Task] /usr/bin:/bin:/usr/sbin:/sbin
10:55:43.945 [DEBUG] [org.gradle.api.Task] /usr/bin:/bin:/usr/sbin:/sbin
```

Whereas on the command line, I get:

```
10:58:32.798 [DEBUG] [org.gradle.api.Task] /opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10:58:32.799 [DEBUG] [org.gradle.api.Task] /opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

I have no idea what is causing this. I suspect it is in the way AS invokes gradle.

> when running with ./gradlew assemble it hangs on overlayiconDebug task (we waited for 2 minutes)

I think this is caused by your project not having a git repository. then the calls to "git" come back empty and the plugin invokes convert trying to overlay with an empty string. this makes convert hang and use 100%. To confirm, can you check if the "convert" process is running while it hangs in `./gradlew assemble`?

**Comment by mg6maciej** [comment] 2015-03-14 13:06
I will not be able to confirm that, becasue @OrdonTeam decided to install Ubuntu on his machine.

So this is not an issue for us anymore, but I'll leave this issue open.

Thanks for your work. It's pretty useful to have an overlay.

Cheers!

**Comment by splatte** [comment] 2015-03-28 22:08
i have released a new version that hopefully makes getting started a bit easier with more output to the user and not failing the build so fast

as to the $PATH problem, i couldn't figure out what to do about it, i guess it's in the way AS invokes gradle. I see two solutions:
1. work with symbolic links, like linking /usr/bin/convert to /opt/local/bin/convert
2.  specify the location of "convert" in build.gradle `appiconoverlay { imageMagick path_to_convert }` and then set `path_to_convert=/opt/local/bin/convert` in `gradle.properties`. this way it can be configured on a "per computer" basis.

**Comment by splatte** [comment] 2015-04-23 15:18
closing this for now. there are workarounds available and this plugin is more verbose about the error to ease troubleshooting

**Closed as completed by splatte** 2015-04-23 15:18 UTC
